### ISSUE TITLE
Delete Session Page

### ISSUE THREAD

**Issue by bridges-wood** [CM10313-Group-1/tempest#16]
- [x] Add a general session page where the user can access viewing, deleting and adding sessions
- [x] Add a delete session page
- [x] The page has a drop-down for selecting modules (also have an option of “All”)
- [x] The relevant sessions are shown in a JTable
- [x] Table is populated by populating a 2D array with all of a module's study session’s date and duration as well as the module name.
- [x] Delete button at the bottom of the table
- [x] When pressed calls module.removeSession(session)
- [x] Session comes from the selected row when the button was pressed

**Comment by Drayz64** [comment]
- [ ] Fix broken tests
- [ ] Write tests for session manager page
- [ ] Write tests for deleting sessions page
