### ISSUE TITLE
Delete Module Page

### ISSUE THREAD

**Issue by bridges-wood** [CM10313-Group-1/tempest#18]
- [x] Add a general modules page where the user can access adding a module and deleting a module
- [x] Add a delete module page
- [x] Has a dropdown for selecting existing modules (use the drop-down class to get this)
- [x] Has a delete button
- [x] When pressed, it calls deleteModule(String moduleName) in State and removeModule() in the drop-down class

**Comment by JoshRenton** [comment]
This is done.
