### ISSUE TITLE
Chart View Controls

### ISSUE THREAD

**Issue by ihussain0910** [CM10313-Group-1/tempest#29]
- [ ] Add and remove modules from the study graph.
- [x] Change module displayed color.

**Comment by Drayz64** [comment]
Just writing this here so I don't forget:

- [ ] Chart Controls Button taking to a chart controls page
- [ ] In this page can select the colours of the different modules for all the charts
- [ ] This page has a default button to set default colours (that we've selected)
- [ ] This page has an enter button - when pressed it runs a over an array list of charts (classes that extend chart) - calling c.setColour()
- [ ] In this method we have the following code

```java
for (Module m : state.getModules()) {
    renderer.setSeriesPaint(dataset.indexOf(m.getName()), m.getColour());
    OR
    renderer.setSeriesPaint(dataset.indexOf(m.getName()), chartControls.getColour(m.getName());
}
```
