### ISSUE TITLE
Broken Page Views

### ISSUE THREAD

**Issue by bridges-wood** [CM10313-Group-1/tempest#46]
**Describe the bug**
When rendering the CardLayout for all the pages, the frame isn't large enough to display everything when switching to certain pages.

**To Reproduce**
1. Open tempest
2. Click on "View Data"

**Expected behavior**
Each of the pages should fill the frame, and if the frame is too small to display a particular page, it should either be scrollable, the content be resized to fit, or the frame should be made larger.

**Comment by Drayz64** [comment]
Closing this because GitHub doesn't want to
